module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'security',
        'deps',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'web',
        'api-gateway',
        'auth',
        'assets',
        'scanner',
        'vuln',
        'ai',
        'reporting',
        'notifications',
        'compliance',
        'billing',
        'websocket',
        'database',
        'shared',
        'ui',
        'scanner-sdk',
        'ai-sdk',
        'config',
        'infra',
        'docker',
        'k8s',
        'helm',
        'terraform',
        'ci',
        'deps',
        'global',
      ],
    ],
    'subject-max-length': [2, 'always', 100],
    'body-max-line-length': [2, 'always', 200],
  },
};
